### ISSUE TITLE
Issue with light theme

### ISSUE THREAD

**Issue by morisrc** [godlyranchdressing/United-GNOME#165]
HI,
when I use the light theme, the buttons disappear in the windows that use the dark theme, like Tilix or Gthumb
I use your latest uploaded version (via Github) in gnome 3.26
![schermata da 2017-11-01 11-13-00](https://user-images.githubusercontent.com/20545323/32270471-581f0f3a-bef6-11e7-94ed-edfb2e322272.png)

**Comment by sharifzadesina** [comment]
@godlyranchdressing Dude can you please fix this issue? this is really annoying...

**Comment by godlyranchdressing** [comment]
@sharifzadesina I think this has been fixed for a while now. I double checked and there's no issue. Maybe you can try redownloading the theme?

**Comment by morisrc** [comment]
@godlyranchdressing I've redownloading the arch-compact.tar and put the 4 folders in the .themes folder (is that the right way to get the fix?) But the problem is still here :-(

**Comment by sharifzadesina** [comment]
@godlyranchdressing No dude, I am using last version from master, It is not fixed.

**Comment by godlyranchdressing** [comment]
@sharifzadesina what variant are you using? Are you both using the compact theme?

**Comment by sharifzadesina** [comment]
@godlyranchdressing Yes dude, I am using archlinux-compact

**Comment by godlyranchdressing** [comment]
So... whoops. I just pushed the fix. Sorry about that, there was a problem with the script for the compact theme not copying the window button files. Can you try it again?

**Comment by sharifzadesina** [comment]
@godlyranchdressing Yes dude it is now fixed, thank you. everything is now fine, thank you for great work.

**Comment by godlyranchdressing** [comment]
Great! Sorry it took so long for me to notice this. I kept testing the non-compact version.
